// src/lib/components/SettingsModal.svelte
<script lang="ts">
  import { X, CheckCircle2, AlertCircle, Play } from '@lucide/svelte';
  import { createEventDispatcher, onMount } from 'svelte';
  import { showToast } from '$lib/stores/toast';

  const dispatch = createEventDispatcher();

  let { show = false }: { show?: boolean } = $props();

  let settings = $state({
    openaiKey: '',
    openaiBaseUrl: '',
    openaiKeys: [] as string[],
    openaiModel: 'deepseek-chat',
    litellmBaseUrl: '',
    litellmKeys: [] as string[],
    litellmModel: 'deepseek-chat',
    mistralBaseUrl: '',
    mistralKeys: [] as string[],
    mistralModel: 'mistral-large-latest',
    openrouterKey: '',
    openrouterModel: 'deepseek/deepseek-chat',
    defaultModel: 'gemini-2.5-flash',
    maxRetries: 3,
    baseDelay: 2000,
    maxDelay: 30000,
    concurrencyLimit: 5
  });

  let saving = $state(false);

  // Test states
  let testingStatus = $state<Record<string, { loading: boolean, success?: boolean, error?: string }>>({
      custom: { loading: false },
      litellm: { loading: false },
      openrouter: { loading: false },
      mistral: { loading: false }
  });

  const modelOptions = [
    { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash (Default)' },
    { id: 'custom', name: 'Custom OpenAI' },
    { id: 'litellm', name: 'LiteLLM' },
    { id: 'openrouter', name: 'OpenRouter' },
    { id: 'mistral', name: 'Mistral' }
  ];

  onMount(async () => {
    try {
      const res = await fetch('/api/settings');
      const data = await res.json();
      if (data) {
        settings = { ...settings, ...data };
      }
      if (!settings.openaiKeys) settings.openaiKeys = [];
      if (!settings.litellmKeys) settings.litellmKeys = [];
      if (!settings.mistralKeys) settings.mistralKeys = [];
      if (!settings.litellmBaseUrl) settings.litellmBaseUrl = '';
      if (!settings.openrouterKey) settings.openrouterKey = '';
      if (!settings.openaiBaseUrl) settings.openaiBaseUrl = '';
      if (!settings.openaiModel) settings.openaiModel = 'deepseek-chat';
      if (!settings.litellmModel) settings.litellmModel = 'deepseek-chat';
      if (!settings.openrouterModel) settings.openrouterModel = 'deepseek/deepseek-chat';
      if (!settings.defaultModel) settings.defaultModel = 'gemini-2.5-flash';
      if (settings.maxRetries === undefined) settings.maxRetries = 3;
      if (settings.baseDelay === undefined) settings.baseDelay = 2000;
      if (settings.maxDelay === undefined) settings.maxDelay = 30000;
      if (settings.concurrencyLimit === undefined) settings.concurrencyLimit = 5;
    } catch(e) {}
  });

  async function handleSave() {
    saving = true;
    try {
      await fetch('/api/settings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(settings)
      });
      showToast('success', 'Settings saved');
      dispatch('close');
    } catch (error) {
      showToast('error', 'Failed to save settings');
    } finally {
      saving = false;
    }
  }

  async function testConnection(provider: string) {
      testingStatus[provider] = { loading: true };

      let config = {};
      if (provider === 'custom') {
          config = {
              baseUrl: settings.openaiBaseUrl,
              key: settings.openaiKeys[0] || '',
              model: settings.openaiModel
          };
      } else if (provider === 'litellm') {
          config = {
              baseUrl: settings.litellmBaseUrl,
              key: settings.litellmKeys[0] || '',
              model: settings.litellmModel
          };
      } else if (provider === 'mistral') {
              const keys = settings.mistralKeys?.filter((k: string) => k && k.trim() !== '');
              if (!keys || keys.length === 0) throw new Error('API key required');
              config = {
                  baseUrl: settings.mistralBaseUrl || 'https://api.mistral.ai/v1',
                  key: keys[0],
                  model: settings.mistralModel || 'mistral-large-latest'
              }; } else if (provider === 'openrouter') {
          config = {
              key: settings.openrouterKey,
              model: settings.openrouterModel
          };
      }

      try {
          const res = await fetch('/api/test-translation', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ provider, config })
          });

          const data = await res.json();
          if (data.success) {
              testingStatus[provider] = { loading: false, success: true };
          } else {
              testingStatus[provider] = { loading: false, success: false, error: data.error };
          }
      } catch (err: any) {
          testingStatus[provider] = { loading: false, success: false, error: err.message };
      }

      setTimeout(() => {
          if (testingStatus[provider]) {
             testingStatus[provider].success = undefined;
             testingStatus[provider].error = undefined;
          }
      }, 3000);
  }

  function handleKeyChange(index: number, e: Event) {
      const val = (e.target as HTMLInputElement).value;
      settings.openaiKeys[index] = val;
  }
  function addKey() {
      settings.openaiKeys = [...settings.openaiKeys, ''];
  }

  function removeKey(index: number) {
      settings.openaiKeys = settings.openaiKeys.filter((_, i) => i !== index);
  }

  function handleLitellmKeyChange(index: number, e: Event) {
      const val = (e.target as HTMLInputElement).value;
      settings.litellmKeys[index] = val;
  }
  function addLitellmKey() {
      settings.litellmKeys = [...settings.litellmKeys, ''];
  }
  function removeLitellmKey(index: number) {
      settings.litellmKeys = settings.litellmKeys.filter((_, i) => i !== index);
  }

  function handleMistralKeyChange(index: number, event: Event) {
      const target = event.target as HTMLInputElement;
      settings.mistralKeys[index] = target.value;
  }

  function addMistralKey() {
      settings.mistralKeys = [...settings.mistralKeys, ''];
  }

  function removeMistralKey(index: number) {
      settings.mistralKeys = settings.mistralKeys.filter((_: any, i: number) => i !== index);
  }


</script>

{#if show}
  <div class="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50 font-sans text-[#1a1a1a]">
    <div class="bg-[#fcfaf7] rounded-[10px] shadow-2xl max-w-xl w-full p-8 relative border border-[#e5e5e5]">
      <button 
        onclick={() => dispatch('close')}
        class="absolute top-6 right-6 text-gray-400 hover:text-gray-900 transition-colors"
      >
        <X class="w-6 h-6" />
      </button>
      
      <h2 class="text-2xl font-bold mb-8 tracking-tight">Translation Settings</h2>
      
      <div class="space-y-8 max-h-[65vh] overflow-y-auto pr-4 scrollbar-thin">
        
        <!-- Global Default Provider -->
        <div class="space-y-3 bg-white p-5 rounded-[10px] border border-[#e5e5e5] shadow-sm">
          <h3 class="font-semibold text-lg text-gray-900">Default Model</h3>
          <p class="text-sm text-gray-500 mb-2">Select the default model to use for translating new books.</p>
          <select
            bind:value={settings.defaultModel}
            class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
          >
            {#each modelOptions as opt}
              <option value={opt.id}>{opt.name}</option>
            {/each}
          </select>
        </div>


        <!-- Advanced Translation Settings -->
        <div class="space-y-4 bg-white p-5 rounded-[10px] border border-[#e5e5e5] shadow-sm">
          <h3 class="font-semibold text-lg text-gray-900">Advanced API Settings</h3>
          <p class="text-sm text-gray-500 mb-2">Configure retry logic and concurrency for API calls.</p>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5" for="maxRetries">
                Max Retries
              </label>
              <input
                id="maxRetries"
                type="number"
                min="0"
                bind:value={settings.maxRetries}
                class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5" for="concurrencyLimit">
                Concurrency Limit
              </label>
              <input
                id="concurrencyLimit"
                type="number"
                min="1"
                bind:value={settings.concurrencyLimit}
                class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5" for="baseDelay">
                Base Delay (ms)
              </label>
              <input
                id="baseDelay"
                type="number"
                min="100"
                step="100"
                bind:value={settings.baseDelay}
                class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5" for="maxDelay">
                Max Delay (ms)
              </label>
              <input
                id="maxDelay"
                type="number"
                min="1000"
                step="1000"
                bind:value={settings.maxDelay}
                class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
              />
            </div>
          </div>
        </div>

        <!-- Custom OpenAI -->
        <div class="space-y-4 bg-white p-5 rounded-[10px] border border-[#e5e5e5] shadow-sm">
          <div class="flex justify-between items-center mb-2">
              <h3 class="font-semibold text-lg text-gray-900">Custom OpenAI</h3>
              <button
                onclick={() => testConnection('custom')}
                disabled={testingStatus.custom.loading}
                class="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-[#2563eb] bg-blue-50 hover:bg-blue-100 rounded-[10px] transition-colors disabled:opacity-50"
              >
                  {#if testingStatus.custom.loading}
                      <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-[#2563eb]"></div>
                      <span>Testing...</span>
                  {:else if testingStatus.custom.success}
                      <CheckCircle2 class="w-4 h-4 text-green-500" />
                      <span class="text-green-600">Success</span>
                  {:else if testingStatus.custom.error}
                      <AlertCircle class="w-4 h-4 text-red-500" />
                      <span class="text-red-600">Failed</span>
                  {:else}
                      <Play class="w-4 h-4" />
                      <span>Test</span>
                  {/if}
              </button>
          </div>

          {#if testingStatus.custom.error}
              <div class="text-xs text-red-500 bg-red-50 p-2 rounded-[10px]">{testingStatus.custom.error}</div>
          {/if}

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="baseUrl">
              Base URL
            </label>
            <input
              id="baseUrl"
              type="text"
              bind:value={settings.openaiBaseUrl}
              placeholder="e.g. https://api.openai.com/v1"
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="openaiModel">
              Model Name
            </label>
            <input
              id="openaiModel"
              type="text"
              bind:value={settings.openaiModel}
              placeholder="e.g. deepseek-chat"
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>

          <div>
              <span class="block text-sm font-medium text-gray-700 mb-1.5">
                API Keys (round-robin)
              </span>
              {#each settings.openaiKeys as key, i}
                  <div class="flex gap-2 mb-2">
                      <input
                          type="password"
                          value={key}
                          oninput={(e) => handleKeyChange(i, e)}
                          placeholder="sk-..."
                          class="flex-1 border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
                      />
                      <button type="button" onclick={() => removeKey(i)} class="p-2.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-[10px] transition-colors">
                          <X class="w-4 h-4" />
                      </button>
                  </div>
              {/each}
              <button type="button" onclick={addKey} class="text-[#2563eb] hover:text-[#1d4ed8] text-sm font-medium mt-1">
                  + Add another key
              </button>
          </div>
        </div>

        <!-- LiteLLM -->
        <div class="space-y-4 bg-white p-5 rounded-[10px] border border-[#e5e5e5] shadow-sm">
           <div class="flex justify-between items-center mb-2">
              <h3 class="font-semibold text-lg text-gray-900">LiteLLM Proxy</h3>
              <button
                onclick={() => testConnection('litellm')}
                disabled={testingStatus.litellm.loading}
                class="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-[#2563eb] bg-blue-50 hover:bg-blue-100 rounded-[10px] transition-colors disabled:opacity-50"
              >
                  {#if testingStatus.litellm.loading}
                      <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-[#2563eb]"></div>
                      <span>Testing...</span>
                  {:else if testingStatus.litellm.success}
                      <CheckCircle2 class="w-4 h-4 text-green-500" />
                      <span class="text-green-600">Success</span>
                  {:else if testingStatus.litellm.error}
                      <AlertCircle class="w-4 h-4 text-red-500" />
                      <span class="text-red-600">Failed</span>
                  {:else}
                      <Play class="w-4 h-4" />
                      <span>Test</span>
                  {/if}
              </button>
          </div>

          {#if testingStatus.litellm.error}
              <div class="text-xs text-red-500 bg-red-50 p-2 rounded-[10px]">{testingStatus.litellm.error}</div>
          {/if}

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="litellmBaseUrl">
              Base URL
            </label>
            <input
              id="litellmBaseUrl"
              type="text"
              bind:value={settings.litellmBaseUrl}
              placeholder="e.g. https://your-litellm-proxy.com"
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="litellmModel">
              Model Name
            </label>
            <input
              id="litellmModel"
              type="text"
              bind:value={settings.litellmModel}
              placeholder="e.g. deepseek-chat"
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>

          <div>
              <span class="block text-sm font-medium text-gray-700 mb-1.5">
                API Keys (round-robin)
              </span>
              {#each settings.litellmKeys as key, i}
                  <div class="flex gap-2 mb-2">
                      <input
                          type="password"
                          value={key}
                          oninput={(e) => handleLitellmKeyChange(i, e)}
                          placeholder="sk-..."
                          class="flex-1 border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
                      />
                      <button type="button" onclick={() => removeLitellmKey(i)} class="p-2.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-[10px] transition-colors">
                          <X class="w-4 h-4" />
                      </button>
                  </div>
              {/each}
              <button type="button" onclick={addLitellmKey} class="text-[#2563eb] hover:text-[#1d4ed8] text-sm font-medium mt-1">
                  + Add another key
              </button>
          </div>
        </div>

        <!-- OpenRouter -->
        <div class="space-y-4 bg-white p-5 rounded-[10px] border border-[#e5e5e5] shadow-sm">
           <div class="flex justify-between items-center mb-2">
              <h3 class="font-semibold text-lg text-gray-900">OpenRouter</h3>
              <button
                onclick={() => testConnection('openrouter')}
                disabled={testingStatus.openrouter.loading}
                class="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-[#2563eb] bg-blue-50 hover:bg-blue-100 rounded-[10px] transition-colors disabled:opacity-50"
              >
                  {#if testingStatus.openrouter.loading}
                      <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-[#2563eb]"></div>
                      <span>Testing...</span>
                  {:else if testingStatus.openrouter.success}
                      <CheckCircle2 class="w-4 h-4 text-green-500" />
                      <span class="text-green-600">Success</span>
                  {:else if testingStatus.openrouter.error}
                      <AlertCircle class="w-4 h-4 text-red-500" />
                      <span class="text-red-600">Failed</span>
                  {:else}
                      <Play class="w-4 h-4" />
                      <span>Test</span>
                  {/if}
              </button>
          </div>

          {#if testingStatus.openrouter.error}
              <div class="text-xs text-red-500 bg-red-50 p-2 rounded-[10px]">{testingStatus.openrouter.error}</div>
          {/if}

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="openrouterModel">
              Model Name
            </label>
            <input
              id="openrouterModel"
              type="text"
              bind:value={settings.openrouterModel}
              placeholder="e.g. deepseek/deepseek-chat"
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="openrouterKey">
              API Key
            </label>
            <input
              id="openrouterKey"
              type="password"
              bind:value={settings.openrouterKey}
              placeholder="sk-or-v1-..."
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>
        </div>

        <!-- Mistral -->
        <div class="space-y-4 bg-white p-5 rounded-[10px] border border-[#e5e5e5] shadow-sm">
           <div class="flex justify-between items-center mb-2">
              <h3 class="font-semibold text-lg text-gray-900">Mistral</h3>
              <button
                onclick={() => testConnection('mistral')}
                disabled={testingStatus.mistral.loading}
                class="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-[#2563eb] bg-blue-50 hover:bg-blue-100 rounded-[10px] transition-colors disabled:opacity-50"
              >
                  {#if testingStatus.mistral.loading}
                      <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-[#2563eb]"></div>
                      <span>Testing...</span>
                  {:else if testingStatus.mistral.success}
                      <CheckCircle2 class="w-4 h-4 text-green-500" />
                      <span class="text-green-600">Success</span>
                  {:else if testingStatus.mistral.error}
                      <AlertCircle class="w-4 h-4 text-red-500" />
                      <span class="text-red-600">Failed</span>
                  {:else}
                      <Play class="w-4 h-4" />
                      <span>Test</span>
                  {/if}
              </button>
          </div>

          {#if testingStatus.mistral.error}
              <div class="text-xs text-red-500 bg-red-50 p-2 rounded-[10px]">{testingStatus.mistral.error}</div>
          {/if}

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="mistralBaseUrl">
              Base URL (Optional)
            </label>
            <input
              id="mistralBaseUrl"
              type="text"
              bind:value={settings.mistralBaseUrl}
              placeholder="e.g. https://api.mistral.ai/v1"
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1.5" for="mistralModel">
              Model Name
            </label>
            <input
              id="mistralModel"
              type="text"
              bind:value={settings.mistralModel}
              placeholder="e.g. mistral-large-latest"
              class="w-full border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
            />
          </div>

          <div>
              <span class="block text-sm font-medium text-gray-700 mb-1.5">
                API Keys (round-robin)
              </span>
              {#each settings.mistralKeys as key, i}
                  <div class="flex gap-2 mb-2">
                      <input
                          type="password"
                          value={key}
                          oninput={(e) => handleMistralKeyChange(i, e)}
                          placeholder="API Key"
                          class="flex-1 border border-gray-300 rounded-[10px] p-2.5 text-sm focus:ring-[#2563eb] focus:border-[#2563eb] outline-none"
                      />
                      <button type="button" onclick={() => removeMistralKey(i)} class="p-2.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-[10px] transition-colors">
                          <X class="w-4 h-4" />
                      </button>
                  </div>
              {/each}
              <button type="button" onclick={addMistralKey} class="text-[#2563eb] hover:text-[#1d4ed8] text-sm font-medium mt-1">
                  + Add another key
              </button>
          </div>
        </div>


      </div>

      <div class="pt-8 mt-4 border-t border-[#e5e5e5] flex justify-end gap-3">
        <button
          onclick={() => dispatch('close')}
          class="px-5 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-100 rounded-[10px] transition-colors"
        >
          Cancel
        </button>
        <button
          onclick={handleSave}
          disabled={saving}
          class="px-5 py-2.5 text-sm font-medium bg-[#2563eb] text-white rounded-[10px] hover:bg-[#1d4ed8] disabled:opacity-50 transition-colors shadow-sm"
        >
          {saving ? 'Saving...' : 'Save Changes'}
        </button>
      </div>
    </div>
  </div>
{/if}

// src/components/SettingsModal.tsx
import React, { useState, useEffect } from 'react';
import { X, Save, RefreshCw, Plus, Trash2 } from 'lucide-react';
import { settingsStore } from '../lib/db';
import { cn } from '../lib/utils';

interface SettingsModalProps {
  onClose: () => void;
  onSettingsSaved: () => void;
}

export interface AppSettings {
  openaiBaseUrl: string;
  openaiKey: string;
  openaiKeys?: string[];
  customModels: { id: string; name: string }[];
}

export function SettingsModal({ onClose, onSettingsSaved }: SettingsModalProps) {
  const [loading, setLoading] = useState(false);
  const [fetchingModels, setFetchingModels] = useState(false);
  const [settings, setSettings] = useState<AppSettings>({
    openaiBaseUrl: 'https://api.openai.com/v1',
    openaiKey: '',
    openaiKeys: [''],
    customModels: []
  });
  const [message, setMessage] = useState<{ type: 'success'|'error', text: string } | null>(null);

  useEffect(() => {
    async function loadSettings() {
      const saved = await settingsStore.getItem<AppSettings>('app_settings');
      if (saved) {
        const openaiKeys = saved.openaiKeys && saved.openaiKeys.length > 0
          ? saved.openaiKeys
          : saved.openaiKey ? [saved.openaiKey] : [''];
        setSettings({ ...saved, openaiKeys });
      }
    }
    loadSettings();
  }, []);

  const handleSave = async () => {
    setLoading(true);
    try {
      const validKeys = (settings.openaiKeys || []).filter(k => k.trim() !== '');
      const finalKeys = validKeys.length > 0 ? validKeys : [''];
      const toSave = {
        ...settings,
        openaiKeys: finalKeys,
        openaiKey: finalKeys[0]
      };
      await settingsStore.setItem('app_settings', toSave);
      setSettings(toSave);
      setMessage({ type: 'success', text: 'Settings saved successfully.' });
      onSettingsSaved();
      setTimeout(onClose, 1000);
    } catch (e) {
      setMessage({ type: 'error', text: 'Failed to save settings.' });
    } finally {
      setLoading(false);
    }
  };

  const handleFetchModels = async () => {
    const validKeys = (settings.openaiKeys || []).filter(k => k.trim() !== '');
    const keyToUse = validKeys.length > 0 ? validKeys[0] : settings.openaiKey;
    if (!settings.openaiBaseUrl || !keyToUse) {
      setMessage({ type: 'error', text: 'Base URL and at least one API Key are required to fetch models.' });
      return;
    }

    setFetchingModels(true);
    setMessage(null);
    try {
      const url = settings.openaiBaseUrl.endsWith('/') 
        ? `${settings.openaiBaseUrl}models` 
        : `${settings.openaiBaseUrl}/models`;

      // Depending on CORS, this might fail from browser without a proxy if the custom API doesn't support it, but we try anyway since it's a "custom" endpoint often hosted by user with cors enabled or through a local proxy.
      const response = await fetch(url, {
        headers: {
          'Authorization': `Bearer ${keyToUse}`,
          'Accept': 'application/json'
        }
      });

      if (!response.ok) {
        throw new Error(`Error ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();
      if (data.data && Array.isArray(data.data)) {
        const models = data.data.map((m: any) => ({
          id: m.id,
          name: m.id // some endpoints don't provide a nice name
        }));
        setSettings(s => ({ ...s, customModels: models }));
        setMessage({ type: 'success', text: `Fetched ${models.length} models successfully.` });
      } else {
        throw new Error('Unexpected response format.');
      }
    } catch (e: any) {
      setMessage({ type: 'error', text: e.message || 'Failed to fetch models.' });
    } finally {
      setFetchingModels(false);
    }
  };

  const addApiKey = () => {
    setSettings(s => ({ ...s, openaiKeys: [...(s.openaiKeys || []), ''] }));
  };

  const updateApiKey = (index: number, value: string) => {
    setSettings(s => {
      const newKeys = [...(s.openaiKeys || [])];
      newKeys[index] = value;
      return { ...s, openaiKeys: newKeys };
    });
  };

  const removeApiKey = (index: number) => {
    setSettings(s => {
      const newKeys = [...(s.openaiKeys || [])];
      newKeys.splice(index, 1);
      if (newKeys.length === 0) newKeys.push('');
      return { ...s, openaiKeys: newKeys };
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm px-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col font-inter">
        <div className="flex items-center justify-between p-6 border-b border-divider">
          <h2 className="font-playfair text-xl font-bold text-ink">Settings</h2>
          <button onClick={onClose} className="p-2 hover:bg-black/5 rounded-full transition-colors text-accent hover:text-ink">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 overflow-y-auto space-y-6">
          {message && (
            <div className={cn("px-4 py-3 rounded text-sm", message.type === 'error' ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700')}>
              {message.text}
            </div>
          )}

          <div className="space-y-4">
            <div>
              <h3 className="text-base font-semibold text-ink mb-1">Custom OpenAI Endpoint</h3>
              <p className="text-xs text-accent mb-4">Connect to any OpenAI-compatible API (e.g., DeepSeek, Groq, Ollama, vLLM).</p>
            </div>

            <div className="space-y-1.5">
              <label className="text-sm font-medium text-ink">Base URL</label>
              <input 
                type="text" 
                value={settings.openaiBaseUrl}
                onChange={e => setSettings(s => ({...s, openaiBaseUrl: e.target.value}))}
                placeholder="https://api.openai.com/v1"
                className="w-full px-3 py-2 border border-divider rounded-md focus:outline-none focus:border-ink transition-colors text-sm"
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium text-ink">API Keys (Load Balanced)</label>
              <div className="space-y-2">
                {(settings.openaiKeys || []).map((key, idx) => (
                  <div key={idx} className="flex items-center gap-2">
                    <input
                      type="password"
                      value={key}
                      onChange={e => updateApiKey(idx, e.target.value)}
                      placeholder="sk-..."
                      className="flex-1 px-3 py-2 border border-divider rounded-md focus:outline-none focus:border-ink transition-colors text-sm"
                    />
                    <button onClick={() => removeApiKey(idx)} className="p-2 text-accent hover:text-red-500 transition-colors" title="Remove Key">
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
              <button
                onClick={addApiKey}
                className="flex items-center gap-1 text-sm font-medium text-ink hover:text-black transition-colors"
              >
                <Plus className="w-4 h-4" /> Add API Key
              </button>
            </div>

            <div className="pt-2">
              <button 
                onClick={handleFetchModels}
                disabled={fetchingModels}
                className="flex items-center gap-2 px-4 py-2 border border-divider rounded-md text-sm font-medium hover:bg-black/5 transition-colors disabled:opacity-50"
              >
                {fetchingModels ? <RefreshCw className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
                Fetch Models
              </button>
            </div>

            {settings.customModels.length > 0 && (
              <div className="mt-4">
                <label className="text-sm font-medium text-ink mb-2 block">Available Custom Models ({settings.customModels.length})</label>
                <div className="max-h-32 overflow-y-auto border border-divider rounded-md bg-paper p-2">
                  <ul className="text-xs text-accent space-y-1">
                    {settings.customModels.map(m => (
                      <li key={m.id} className="truncate px-2 py-1 hover:bg-black/5 rounded">{m.id}</li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="p-6 border-t border-divider flex justify-end gap-3 bg-paper/50">
          <button 
            onClick={onClose}
            className="px-4 py-2 border border-divider rounded-md text-sm font-medium hover:bg-white transition-colors"
          >
            Cancel
          </button>
          <button 
            onClick={handleSave}
            disabled={loading}
            className="flex items-center gap-2 px-6 py-2 bg-ink text-white rounded-md text-sm font-medium hover:bg-[#333] transition-colors disabled:opacity-50"
          >
            <Save className="w-4 h-4" /> Save Settings
          </button>
        </div>
      </div>
    </div>
  );
}
